# Generated by Django 6.0.7 on 2026-07-17 14:49

from django.db import migrations, models


def migrate_approval_to_status(apps, schema_editor):
    Review = apps.get_model("product_page", "Review")
    Review.objects.filter(is_approved=True).update(status="approved")
    Review.objects.filter(is_approved=False).update(status="pending")


def migrate_status_to_approval(apps, schema_editor):
    Review = apps.get_model("product_page", "Review")
    Review.objects.update(is_approved=False)
    Review.objects.filter(status="approved").update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0002_populate_product_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.RunPython(
            migrate_approval_to_status,
            migrate_status_to_approval,
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
    ]
